name: exFAT Extractor Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Multi-Platform Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, macos]
        include:
          - platform: linux
            ext: ""
            goos: linux
            goarch: amd64
          - platform: windows
            ext: ".exe"
            goos: windows
            goarch: amd64
          - platform: macos
            ext: ""
            goos: darwin
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Initialize Go module
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/${{ github.repository }}/exfat-extractor
        fi
        go get github.com/dsoprea/go-exfat@latest
        go get github.com/dsoprea/go-logging@latest
        go get github.com/jessevdk/go-flags@latest
        go mod tidy

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        mkdir -p release
        go build -v -trimpath -ldflags="-s -w" -o "release/exfat-extractor-${{ matrix.platform }}${{ matrix.ext }}" .

    # 将所有文件收集到一个 Artifact
    - name: Upload all artifacts
      if: matrix.platform == 'macos' # 只在最后一步上传
      uses: actions/upload-artifact@v4
      with:
        name: exfat-extractor-binaries-${{ github.run_number }}
        path: release/
        retention-days: 7
