name: exFAT Extractor Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Multi-Platform Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, macos]
        include:
          - platform: linux
            ext: ""
            goos: linux
            goarch: amd64
            artifact_name: exfat-extractor-linux
          - platform: windows
            ext: ".exe"
            goos: windows
            goarch: amd64
            artifact_name: exfat-extractor-windows
          - platform: macos
            ext: ""
            goos: darwin
            goarch: arm64
            artifact_name: exfat-extractor-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Initialize Go module
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/${{ github.repository }}/exfat-extractor
        fi
        go get github.com/dsoprea/go-exfat@latest
        go get github.com/dsoprea/go-logging@latest
        go get github.com/jessevdk/go-flags@latest
        go mod tidy

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        mkdir -p release
        go build -v -trimpath -ldflags="-s -w" -o "release/exfat-extractor${{ matrix.ext }}" .

    - name: Rename binary for artifact
      run: |
        mv "release/exfat-extractor${{ matrix.ext }}" "${{ matrix.artifact_name }}${{ matrix.ext }}"
        echo "Renamed to: ${{ matrix.artifact_name }}${{ matrix.ext }}"

    - name: Upload ${{ matrix.platform }} binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-${{ github.run_number }}
        path: ${{ matrix.artifact_name }}${{ matrix.ext }}
        retention-days: 7
