name: Go Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
        include:
          - platform: linux
            ext: ""
            goos: linux
            goarch: amd64
          - platform: windows
            ext: ".exe"
            goos: windows
            goarch: amd64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # 指定你的 Go 版本

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0  # 禁用 CGO 以获得静态链接的可执行文件
      run: |
        mkdir -p bin
        go build -v -trimpath -ldflags="-s -w" -o "bin/exfat-extractor-${{ matrix.platform }}${{ matrix.ext }}" ./main.go
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: bin/
